//
// BeCalc Button ids and display strings
//

#ifndef _BUTTONS2_H
#define _BUTTONS2_H

#include "MButton.h"

enum button_ids{
	// Scientific buttons
	ID_INT = 0, ID_SIN, ID_ASIN,
	ID_FRAC, ID_COS, ID_ACOS,
	ID_SIGN, ID_TAN, ID_ATAN,
	ID_ABS, ID_SINH, ID_ASINH,
	ID_NCR, ID_COSH, ID_ACOSH,
	ID_NPR, ID_TANH, ID_ATANH,
	ID_COT, ID_COTH, ID_ACOT,
	ID_ACOTH,
	
	// Programmer buttons
	ID_NAND, ID_NOR, ID_CNT,
	ID_MOD, ID_CBIT, ID_TBIT,
	ID_DIV, ID_SBIT, ID_NEG,
	ID_OR, ID_LSL, ID_LSR,
	ID_AND, ID_ROL, ID_ROR,
	ID_XOR, ID_NOT, ID_ASR,
	
	// Statistic buttons
	ID_SETX, ID_SETXY, ID_CS,
	ID_AVGX, ID_AVGY, ID_SUMXY,
	ID_SUMX, ID_SUMY, ID_SIGX,
	ID_SUMX2, ID_SUMY2, ID_SIGY,
	ID_DEVX, ID_DEVY, ID_N,
	
	// Central key cluster
	ID_EXPON, ID_INV, ID_PI, ID_FACT, ID_POWER, ID_SQUARED,
	ID_A, ID_B, ID_C, ID_D, ID_X3, ID_EXP, 
	ID_7, ID_8, ID_9, ID_E, ID_DIVIDE, ID_MEM,
	ID_4, ID_5, ID_6, ID_F, ID_TIMES, ID_MEMPLUS,
	ID_1, ID_2, ID_3, ID_I, ID_MINUS, ID_LBRACE,
	ID_0, ID_PM, ID_DP, ID_EQUAL, ID_PLUS, ID_RBRACE,
	
	// Right key cluster
	ID_SQRT, ID_ROOT, ID_CE,
	ID_CBRT, ID_LN, ID_RAND,
	ID_10POWER, ID_LOG, ID_MIN,
	ID_RE, ID_IM, ID_MAX,
	ID_THETA, ID_TORECT, ID_CONJ,
	ID_ENTER, ID_X, ID_LOG2, ID_FIB, ID_GCD,
	
	// Miscellaneous buttons
	ID_MORTGAGE, ID_CONVERSIONS,
	ID_CLOSE_MORTGAGE, ID_CLOSE_CONVERSIONS,
	ID_CLOSE_PLOT, ID_CLOSE_COMMANDS, ID_CLOSE_ABOUT,
	ID_CLOSE_PREFS, CID_CONVERSIONS, CID_INVERSE,
	
	// Menus
	ID_ABOUT, ID_COMMANDS, ID_SHOW_GUIDE, ID_PLOT,
	ID_DELETE_SEL, ID_DELETE_EQUATIONS, ID_DELETE_VARIABLES,
	ID_DELETE_RESULTS, ID_PREFERENCES,
	ID_EXPORT_EQUATIONS, ID_EXPORT_RESULTS, ID_EXPORT_VARIABLES,
	ID_EXPORT_ALL, ID_EXPORT_MORTGAGE,
	ID_PRINT_EQUATIONS, ID_PRINT_RESULTS, ID_PRINT_VARIABLES,
	ID_PRINT_ALL, ID_PRINT_MORTGAGE, ID_PAGE_SETUP,
	ID_REOPEN_PLOT, ID_CHANGE_PLOT_MENU, ID_REMOVE_PLOTS,
	ID_HOME, ID_REGISTER, ID_WEB_PAGE,
	
	// Others
	ID_UPDATE_VARS, ID_UPDATE_NUMS, ID_CLEAR
};
	
MButton * MakeButton (int32 id, minimax size);
bool IsNumber(int32 id);
bool IsFunction(int32 id);
char * ButtonIs (int32 id);

#endif  // _BUTTONS_H


